### PR TITLE
Make it possible for users to change behavior

### PR DESCRIPTION
**Pull request by Tunous**
By setting the behavior through CoordinatorLayout.DefaultBehavior, we give users possibility to change it through the app:layout_behavior XML attribute.

### CODE REVIEW

**Comment by DmitryMalkovich** [comment]
Hello @Tunous, you are right! Thanks for your pull-request! There are still some an issue with sample app, do you see it?

**Comment by DmitryMalkovich** [comment]
Interesting, when I removed android:fitsSystemWindows="true" from CoordinatorLayout. It helped.

**Comment by Tunous** [comment]
Cool that you managed to solve the issues! May I know what was wrong? I didn't see anything broken when testing it myself.

**Comment by DmitryMalkovich** [comment]
The issue was that a fab was at the left-top instead of right bottom after your changes at least on Marshmallow. See the fix, https://github.com/DmitryMalkovich/circular-with-floating-action-button/pull/11 The problem obviously was not in your changes :)

**Comment by DmitryMalkovich** [comment]
I will release a new version, when the #9 will be fixed :)

**Pull request merged**
